name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'type:enhancement'
      - 'type:feature-request'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'type:bug'
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'
      - 'dependency'
      - 'type:dependency'
exclude-labels:
  - 'skip-changelog'
exclude-contributors:
  - 'svc-wwcoe-ci-admin'
  - 'dependabot'
  - 'dependabot[bot]'
change-template: '* $TITLE by @$AUTHOR in #$NUMBER'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed

  $CHANGES

  ---
  **Full Changelog**: https://github.com/vmware/vrealize-developer-tools/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    title:
      - '/add|implement|support/i'
