import * as all from "com.vmware.pscoe.tests";
import * as subAll from "com.vmware.pscoe.tests/sub";
import TestClass1, { TestClass2, default as TC1, TestClass2 as TC2 } from "com.vmware.pscoe.tests/action1";
import TestClass3, { TestClass4, default as TC3, TestClass4 as TC4 } from "com.vmware.pscoe.tests/action2";
import * as action1All from "com.vmware.pscoe.tests/action1";
import TestSubClass1, { TestSubClass2, default as TSC1, TestSubClass2 as TSC2 } from "com.vmware.pscoe.tests/sub/subaction1";
import TestSubClass3, { TestSubClass4, default as TSC3, TestSubClass4 as TSC4 } from "com.vmware.pscoe.tests/sub/subaction2";
import * as subaction1All from "com.vmware.pscoe.tests/sub/subaction1";

// new TestClass1();
new TestClass1();
// new TestClass2();
new TestClass2();
// new TestClass3;
new TestClass3;
// new TestClass4();
new TestClass4();
// new TestSubClass1();
new TestSubClass1();
// new TestSubClass2();
new TestSubClass2();
// new TestSubClass3();
new TestSubClass3();
// new TestSubClass4();
new TestSubClass4();
// new TC1();
new TC1();
// new TC2();
new TC2();
// new TC3();
new TC3();
// new TC4();
new TC4();
// new TSC1();
new TSC1();
// new TSC2();
new TSC2();
// new TSC3();
new TSC3();
// new TSC4();
new TSC4();
// new all.action1.default();
new all.action1.default();
// new all.action1.TestClass2();
new all.action1.TestClass2();
// new all.action2.default();
new all.action2.default();
// new all.action2.TestClass4();
new all.action2.TestClass4();
// new all.sub.subaction1.default();
new all.sub.subaction1.default();
// new all.sub.subaction1.TestSubClass2();
new all.sub.subaction1.TestSubClass2();
// new all.sub.subaction2.default();
new all.sub.subaction2.default();
// new all.sub.subaction2.TestSubClass4();
new all.sub.subaction2.TestSubClass4();
// new subAll.subaction1.default();
new subAll.subaction1.default();
// new subAll.subaction1.TestSubClass2();
new subAll.subaction1.TestSubClass2();
// new subAll.subaction2.default();
new subAll.subaction2.default();
// new subAll.subaction2.TestSubClass4();
new subAll.subaction2.TestSubClass4();
// new action1All.TestClass2();
new action1All.TestClass2();
// new action1All.default();
new action1All.default();
// new subaction1All.default();
new subaction1All.default();
// new subaction1All.TestSubClass2();
new subaction1All.TestSubClass2();
